### ISSUE TITLE
Sorry, I keep getting redirect_uri_mismatch Error

### ISSUE THREAD

**Issue by ipeisong** [Orange-OpenSource/spring-social-weibo#2]
访问出错了！
你所访问的站点在新浪微博的认证失败，请你联系开发者助手或者稍后再试。
(error:redirect_uri_mismatch)

any suggestion about this? I checked some documents saying one need configure callback to enable the application on weibo? Thanks.

**Comment by dvergnes** [comment]
Did you declare an application on Weibo to configure your client id and client secret? If you did so, check on your configuration application (http://open.weibo.com/apps/) the value of the application callback page (应用回调页)  on following menu: application configuration > advanced configuration (应用信息 > 高级信息).

**Comment by ipeisong** [comment]
it turns out that the url I filled in is missing 'www', I filled in example.com but I was calling www.example.com, that is the cause.
