### ISSUE TITLE
微博指的新浪微博吧

### ISSUE THREAD

**Issue by jokerkiller** [Orange-OpenSource/spring-social-weibo#7]
我看到你们的提交主要集中在2012年，现在还可以用吗？

**Comment by bbailleux** [comment]
Hello _jokerkiller_.
This project is unfortunately unmaintained, and the original author has left the company years ago.
The current repository will be set to the "archived" status today, and no one will work on it :crying_cat_face: , but feel free to fork it if you want.

Note that there is currently 50 forks of this repository. You _may_ (no guarantee) find that one of them could fulfil your needs.
